### PR TITLE
[spec] add an explicit algorithm step for an empty string searchValue

### PR DESCRIPTION
**Pull request by ljharb**
Closes #32.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
This is unnecessary (see https://github.com/tc39/proposal-string-replaceall/issues/32#issuecomment-547749558), but if it helps readability then I guess let’s do it. 🤷🏼‍♂️

I do wonder if this could be an `Assert` of some kind instead, given that:

- this behavior is already covered by another algorithm step, and
- this behavior is already mentioned in a non-normative note.

**Comment by ljharb** [comment]
That other step is very unclear to me, and if there’s a better way to express it I’d prefer that too :-)

**Comment by mathiasbynens** [comment]
Any ideas? Or should we just merge this as-is?

**Comment by ljharb** [comment]
I’d prefer this for now, and I’ll definitely try to find a better way to phrase the confusing step :-) that doesn’t have to block stage 3 or 4, ofc, so it can come at any time.

I find this one important ASAP because its absence combined with the confusion of the step in question caused a bug :-)

**Pull request merged**
