### PR TITLE
add es-shims polyfill

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by zloirock** [comment]
Maybe better sort them by popularity (or at least alphabetical)? -)

**Comment by zloirock** [comment]
2 downloads per week...

**Comment by ljharb** [comment]
it’s only been stage 3 for a few weeks (it’s widely considered a bad practice to ship polyfills to production prior to stage 3), and popularity wouldn’t be relevant anyways.

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
Let’s not make this into a popularity contest. In other proposal repos, I’ve been using insertion order for implementations — let’s keep it that way.

**Comment by ljharb** [comment]
I’d suggest publish order, but your call either way.

**Pull request merged**
